// design-sync build step (cfg.buildCmd). Produces the three generated inputs
// the converter consumes from .design-sync/pkg/ - never edit them by hand:
//   1. yieldtome.css  - app/globals.css compiled through the app's own
//                        Tailwind v4 postcss pipeline (cfg.cssEntry)
//   2. index.ts       - barrel re-exporting every app/components/*.tsx
//                        (the package entry; cfg.entry)
//   3. types/         - tsc declaration emit for that barrel, so the
//                        converter reads real <Name>Props contracts
import { execFileSync } from 'node:child_process';
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import postcss from 'postcss';
import tailwind from '@tailwindcss/postcss';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const pkg = resolve(here, 'pkg');
mkdirSync(pkg, { recursive: true });

// Files under app/components that are wiring, not UI - excluded from the barrel.
const EXCLUDE = new Set(['service-worker-registration.tsx']);

// 1. CSS
{
  const from = resolve(root, 'app/globals.css');
  const to = resolve(pkg, 'yieldtome.css');
  const result = await postcss([tailwind({ base: root })]).process(readFileSync(from, 'utf8'), { from, to, map: false });
  writeFileSync(to, result.css);
  console.error(`  css: app/globals.css -> .design-sync/pkg/yieldtome.css (${result.css.length} bytes)`);
}

// 2. Barrel
{
  const files = readdirSync(resolve(root, 'app/components'))
    .filter((f) => f.endsWith('.tsx') && !EXCLUDE.has(f))
    .sort();
  const body = [
    '// GENERATED by .design-sync/build-pkg.mjs - do not edit.',
    ...files.map((f) => `export * from "../../app/components/${f}";`),
    '',
  ].join('\n');
  writeFileSync(resolve(pkg, 'index.ts'), body);
  console.error(`  barrel: ${files.length} component modules -> .design-sync/pkg/index.ts`);
}

// 3. Declarations
{
  rmSync(resolve(pkg, 'types'), { recursive: true, force: true });
  try {
    execFileSync(resolve(root, 'node_modules/.bin/tsc'), ['-p', resolve(here, 'tsconfig.types.json')], { stdio: 'inherit', cwd: root });
  } catch (e) {
    // tsc still emits on type errors; surface them but keep going.
    console.error(`  ! tsc exited ${e.status} (declarations emitted where possible)`);
  }
  console.error('  types: .design-sync/pkg/types/');
}
