CREATE TABLE `market_data_refresh_jobs` (
	`id` text PRIMARY KEY NOT NULL,
	`provider_id` text NOT NULL,
	`target_kind` text NOT NULL,
	`target_key` text NOT NULL,
	`mapping_id` text,
	`security_id` text,
	`base_currency_code` text,
	`quote_currency_code` text,
	`access_scope` text NOT NULL,
	`scope_user_id` text,
	`scope_key` text NOT NULL,
	`range_from` text NOT NULL,
	`range_to` text NOT NULL,
	`high_water_date` text,
	`chunk_days` integer DEFAULT 5 NOT NULL,
	`status` text DEFAULT 'queued' NOT NULL,
	`attempt` integer DEFAULT 0 NOT NULL,
	`lease_owner` text,
	`lease_expires_at` text,
	`next_attempt_at` text NOT NULL,
	`provider_request_count` integer DEFAULT 0 NOT NULL,
	`observation_count` integer DEFAULT 0 NOT NULL,
	`correction_count` integer DEFAULT 0 NOT NULL,
	`last_error_kind` text,
	`idempotency_key` text NOT NULL,
	`started_at` text,
	`completed_at` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`provider_id`) REFERENCES `market_data_providers`(`id`) ON UPDATE no action ON DELETE restrict,
	FOREIGN KEY (`scope_user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE restrict,
	FOREIGN KEY (`mapping_id`,`provider_id`,`security_id`) REFERENCES `security_provider_mappings`(`id`,`provider_id`,`security_id`) ON UPDATE no action ON DELETE restrict,
	FOREIGN KEY (`base_currency_code`) REFERENCES `currencies`(`code`) ON UPDATE no action ON DELETE restrict,
	FOREIGN KEY (`quote_currency_code`) REFERENCES `currencies`(`code`) ON UPDATE no action ON DELETE restrict,
	CONSTRAINT "market_data_refresh_jobs_target_kind_check" CHECK("market_data_refresh_jobs"."target_kind" IN ('price', 'fx')),
	CONSTRAINT "market_data_refresh_jobs_target_shape_check" CHECK(("market_data_refresh_jobs"."target_kind" = 'price' AND "market_data_refresh_jobs"."mapping_id" IS NOT NULL AND "market_data_refresh_jobs"."security_id" IS NOT NULL AND "market_data_refresh_jobs"."base_currency_code" IS NULL AND "market_data_refresh_jobs"."quote_currency_code" IS NULL) OR ("market_data_refresh_jobs"."target_kind" = 'fx' AND "market_data_refresh_jobs"."mapping_id" IS NULL AND "market_data_refresh_jobs"."security_id" IS NULL AND "market_data_refresh_jobs"."base_currency_code" IS NOT NULL AND "market_data_refresh_jobs"."quote_currency_code" IS NOT NULL AND "market_data_refresh_jobs"."base_currency_code" <> "market_data_refresh_jobs"."quote_currency_code")),
	CONSTRAINT "market_data_refresh_jobs_access_scope_check" CHECK("market_data_refresh_jobs"."access_scope" IN ('deployment', 'user')),
	CONSTRAINT "market_data_refresh_jobs_scope_check" CHECK(("market_data_refresh_jobs"."access_scope" = 'deployment' AND "market_data_refresh_jobs"."scope_user_id" IS NULL AND "market_data_refresh_jobs"."scope_key" = 'deployment') OR ("market_data_refresh_jobs"."access_scope" = 'user' AND "market_data_refresh_jobs"."scope_user_id" IS NOT NULL AND "market_data_refresh_jobs"."scope_key" = "market_data_refresh_jobs"."scope_user_id")),
	CONSTRAINT "market_data_refresh_jobs_range_check" CHECK("market_data_refresh_jobs"."range_to" >= "market_data_refresh_jobs"."range_from"),
	CONSTRAINT "market_data_refresh_jobs_high_water_check" CHECK("market_data_refresh_jobs"."high_water_date" IS NULL OR ("market_data_refresh_jobs"."high_water_date" >= "market_data_refresh_jobs"."range_from" AND "market_data_refresh_jobs"."high_water_date" <= "market_data_refresh_jobs"."range_to")),
	CONSTRAINT "market_data_refresh_jobs_chunk_days_check" CHECK("market_data_refresh_jobs"."chunk_days" BETWEEN 1 AND 5),
	CONSTRAINT "market_data_refresh_jobs_status_check" CHECK("market_data_refresh_jobs"."status" IN ('queued', 'running', 'completed', 'failed')),
	CONSTRAINT "market_data_refresh_jobs_attempt_check" CHECK("market_data_refresh_jobs"."attempt" >= 0),
	CONSTRAINT "market_data_refresh_jobs_provider_request_count_check" CHECK("market_data_refresh_jobs"."provider_request_count" >= 0),
	CONSTRAINT "market_data_refresh_jobs_observation_count_check" CHECK("market_data_refresh_jobs"."observation_count" >= 0),
	CONSTRAINT "market_data_refresh_jobs_correction_count_check" CHECK("market_data_refresh_jobs"."correction_count" >= 0)
);
--> statement-breakpoint
CREATE UNIQUE INDEX `market_data_refresh_jobs_idempotency_unique` ON `market_data_refresh_jobs` (`provider_id`,`scope_key`,`target_kind`,`target_key`,`idempotency_key`);--> statement-breakpoint
CREATE INDEX `market_data_refresh_jobs_claim_idx` ON `market_data_refresh_jobs` (`status`,`next_attempt_at`,`lease_expires_at`);--> statement-breakpoint
CREATE INDEX `market_data_refresh_jobs_target_idx` ON `market_data_refresh_jobs` (`provider_id`,`scope_key`,`target_kind`,`target_key`,`status`);